GET http://localhost:8080/facade
Accept: text/html

###

POST http://localhost:8080/facade
Content-type: application/json

"message 1"

###

POST http://localhost:8080/facade
Content-type: application/json

"message 2"
